/*
 / _____)             _              | |
( (____  _____ ____ _| |_ _____  ____| |__
 \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 _____) ) ____| | | || |_| ____( (___| | | |
(______/|_____)_|_|_| \__)_____)\____)_| |_|
    (C)2015 Semtech

Description: End device commissioning parameters

License: Revised BSD License, see LICENSE.TXT file include in the project

Maintainer: Miguel Luis and Gregory Cristian
*/
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     0

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      true

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
#define IEEE_OUI                                    0x60, 0xC5, 0xA8

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define LORAWAN_DEVICE_EUI                         { 0x00, 0x17, 0xF5, 0xC8, 0x78, 0xB4, 0x62, 0xF8 }

/*!
 * Application IEEE EUI (big endian)
 * PUT YOUR OWN CODE FROM TTN APP LIKE THAT: { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
 */
#define LORAWAN_APPLICATION_EUI                    { 0x70, 0xB3, 0xD5, 0x7E, 0xD0, 0x00, 0x9F, 0xD9 }

/*!
 * AES encryption/decryption cipher application key
 * PUT YOUR OWN CODE FROM TTN APP LIKE THAT: { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0 }
 */
#define LORAWAN_APPLICATION_KEY                     { 0xAF, 0xBB, 0x04, 0xF9, 0xDA, 0xA4, 0x9D, 0x82, 0xB5, 0xC3, 0x07, 0x84, 0x33, 0xCE, 0x4A, 0x17 }

/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x26062cd0

/*!
 * AES encryption/decryption cipher network session key
 */
#define LORAWAN_NWKSKEY                             { 0xCB, 0x4A, 0x86, 0xA5, 0x0A, 0xBF, 0x53, 0x5F, 0x67, 0x11, 0x5C, 0x58, 0xA3, 0x79, 0x85, 0x7F}

/*!
 * AES encryption/decryption cipher application session key
 */
#define LORAWAN_APPSKEY                             { 0x9B, 0x0D, 0xBE, 0xBC, 0x3D, 0x18, 0x13, 0xF1, 0x2E, 0x58, 0x1B, 0x1E, 0x79, 0x79, 0x9B, 0x29 }

#endif // __LORA_COMMISSIONING_H__
